### ISSUE TITLE
random number generator

### ISSUE THREAD

**Issue by lastuniverse** [mhsjlw/flying-squid#75]
Please add a quick pseudo-random number sequences with a large cycle. It will be very useful to write generators landscape.

**Comment by rom1504** [comment]
is that not ok https://github.com/mhsjlw/flying-squid/blob/master/src/lib/serverPlugins/world.js#L16 ?

also see https://github.com/mhsjlw/flying-squid/blob/master/src/lib/worldGenerations/diamond_square.js#L55

This seems to work anyway.

**Comment by lastuniverse** [comment]
OK. thank

**Comment by demipixel** [comment]
Originally we had a seed random number generator. The reason that was important was because the same world seed could be used to generate the exact same biomes and the same chunk seed could be used to generate the exact same chunk (and it was really easy too :P)

**Comment by rom1504** [comment]
And we still do ?!

**Comment by demipixel** [comment]
I mean, I was referencing that seed-random module or whatever it was

**Comment by rom1504** [comment]
Ah yeah, well we might use that, but you were using it with a different seed for each chunk which didn't make sense.

It would probably be better to use that than to use Math.random() like you did [there](https://github.com/mhsjlw/flying-squid/blob/master/src/lib/worldGenerations/diamond_square.js#L110)

**Comment by demipixel** [comment]
Don't quote me on this but I'm pretty sure in vanilla chunk info (biome, height maps, generated structures, caves, etc) are generated by the seed and then everything else (adjusting the height map, trees, ores, grass, and other specific things) are all done randomly (meaning the same seed will never generate these things the same). If you want another seed so that you COULD get the exact same map, that's fine, however as far as I know, that's not how it's done in vanilla.
