### ISSUE TITLE
Support player settings

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#76]
In particular the view setting. See https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/settings.js#L28

**Comment by rom1504** [comment]
Also see view distance in http://minecraft.gamepedia.com/Server.properties

**Comment by demipixel** [comment]
Okay, so the default is 10 in each direction (I don't think we're doing that).

Remember, it says "It determines the server-side viewing distance." so I have no idea why the player sends that option since I don't think the server sends anything different. That option is useful if:

- It's hard for your computer to render the number of chunks the server sends you
- Singleplayer adjusting that distance above the default 10 in each direction.

**Comment by rom1504** [comment]
@demipixel actually the client can send something different, for example my client sends 12 apparently.

currently it's 8, but the only thing to do here is to change player.view when receiving the setting packet.

**Comment by demipixel** [comment]
I'm aware we can do it, I was just curious as to whether or not vanilla did it.
